version: 0.2

phases:
  install:
    commands:
      # Install Node.js (if not using a Node.js AWS image)
      - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - echo "Node.js version: $(node --version)"
      - echo "npm version: $(npm --version)"

      # Install Angular CLI globally
      - npm install -g @angular/cli

  pre_build:
    commands:
      # Install project dependencies
      - npm install

  build:
    commands:
      # Build Angular (replace 'your-app-name' with your actual app name)
      - ng build --prod --output-path=dist

artifacts:
  files:
    - '**/*'  # Deploy all files
  base-directory: 'dist'  # Path where ng build outputs files

cache:
  paths:
    - '/root/.npm/**/*'  # Cache npm to speed up future builds
    - 'node_modules/**/*'
